# Prometheus configuration for WWTP Anomaly Detection System
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'wwtp-anomaly-detection'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rules configuration
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Upload Service  
  - job_name: 'upload-service'
    static_configs:
      - targets: ['upload-service:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Review Service
  - job_name: 'review-service'
    static_configs:
      - targets: ['review-service:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # ML Worker
  - job_name: 'ml-worker'
    static_configs:
      - targets: ['ml-worker:8080']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 15s
    honor_labels: true
    params:
      format: ['prometheus']

  # PostgreSQL
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 15s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 15s

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 15s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 15s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 15s

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 15s
    honor_labels: true

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 30s
    scrape_timeout: 15s

# Relabeling configurations
  # Add instance labels based on job
  - job_name: 'wwtp-services'
    static_configs:
      - targets: 
          - 'auth-service:8000'
          - 'upload-service:8000' 
          - 'review-service:8000'
    metrics_path: /metrics
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'localhost:9090'  # Prometheus proxy